more shellcheck

diff --git a/bin/optli b/bin/optli
--- a/bin/optli
+++ b/bin/optli
@@ -26,11 +26,12 @@ work() {
 		exit 1
 	}
 
-	local oldsize=$(wc -c <"$1")
-	local md5=$(md5sum "$1")
-	md5=${md5%% *}
+	local oldsize newsize md5
 
-	if [[ $oldsize -gt $(( $MAXSIZE*1024*1024 )) ]]; then
+	oldsize=$(wc -c <"$1")
+	md5=$(md5sum "$1"); md5=${md5%% *}
+
+	if [[ $oldsize -gt $(( MAXSIZE*1024*1024 )) ]]; then
 		echo "0 0 too-big $1"
 		exit 0
 	fi
@@ -40,7 +41,8 @@ work() {
 		exit 0
 	fi
 
-	local temp=$(mktemp -u "/tmp/${0##*/}_${1##*/}_XXXXXX") || fail "$1" "tempfile"
+	local temp
+	temp=$(mktemp -u "/tmp/${0##*/}_${1##*/}_XXXXXX") || fail "$1" "tempfile"
 
 	[[ -w "$1" ]] || fail "$1" "no-write-permission"
 	[[ "$(dirname "$1")/" == *"fail/"* ]] && fail "$1" "possible-test-image"
@@ -97,7 +99,7 @@ work() {
 	esac
 
 	[[ -s "$temp" ]] || fail "$1" "new-file-not-created"
-	local newsize=$(wc -c <"$temp")
+	newsize=$(wc -c <"$temp")
 	if [[ $newsize -lt $oldsize ]]; then
 		touch -r "$1" "$temp"
 		trap '' SIGHUP SIGINT SIGQUIT SIGTERM				# don't interrupt while file is being written
@@ -110,8 +112,7 @@ work() {
 		echo "$oldsize $newsize skipping $1"
 	fi
 
-	local md5=$(md5sum "$1")
-	md5=${md5%% *}
+	md5=$(md5sum "$1"); md5=${md5%% *}
 	mkdir -p "$(dirname "$statefile")"
 	echo "$md5" >> "$statefile"
 
@@ -163,14 +164,14 @@ shopt -s lastpipe	# run last pipe element in current shell
 
 # make SURE to only run on type f
 find "$@" \( $pattern \) -type f -print0 \
-	| xargs -r -0 -n1 -P$(getconf _NPROCESSORS_ONLN) bash -c 'work "$@"' _ \
-	| while read oldsize newsize status filename; do
+	| xargs -r -0 -n1 -P"$(getconf _NPROCESSORS_ONLN)" bash -c 'work "$@"' _ \
+	| while read -r oldsize newsize status filename; do
 		echo "$filename: $oldsize → $newsize, $status"
 		total=$(( total + oldsize ))
 		[[ $newsize -lt $oldsize ]] && saved=$(( saved + (oldsize-newsize) ))
 	done
 
 if [[ $total == 0 ]]; then percent=0
-else percent=$(( 100*$saved/$total ))
+else percent=$(( 100*saved/total ))
 fi
-printf "\n\n--------------------------------\nTOTAL SAVED (of changed files):\n   %'.fk / %'.fk ($percent%%)\n" $(($saved/1024)) $(($total/1024))
+printf "\n\n--------------------------------\nTOTAL SAVED (of changed files):\n   %'.fk / %'.fk ($percent%%)\n" $((saved/1024)) $((total/1024))
